version: '3.4'
services:
  elasticsearch-master:
    image: elasticsearch:7.17.20
    container_name: elasticsearch-master

    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=master-node
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=master-node
      - discovery.seed_hosts=elasticsearch-slave
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch-master.rule=Host(`elasticsearch-master.localtest.me`)"
      - "traefik.http.services.elasticsearch-master.loadbalancer.server.port=29200"

  elasticsearch-slave:
    image: elasticsearch:7.17.20
    container_name: elasticsearch-slave
    ports:
      - "29200:9200"
      - "29300:9300"
    environment:
      - node.name=slave-node
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=master-node
      - discovery.seed_hosts=elasticsearch-master
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch-master.rule=Host(`elasticsearch-slave.localtest.me`)"
      - "traefik.http.services.elasticsearch-master.loadbalancer.server.port=9200"

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "28080:8080"
      - "28181:80"
    networks:
      - traefik-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch-master
      - elasticsearch-slave

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: no
    ports:
      - "6380:6379"
    networks:
      - traefik-network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "28001:8001"
      - "5540:5540"
    environment:
      - REDIS_URI=redis://redis:6380
    networks:
      - traefik-network
    depends_on:
      - redis

networks:
  traefik-network:
    driver: bridge
